"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
 and
, the first
 terms will be: 1,2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
class fibbunacci:
    def __init__(self, limiter):
        self.limit = limiter

    def functionsolve(self):
        total_sum = 0
        a, b = 0, 1
        if self.limit == 0:
            return 0
        if self.limit == 1:
            return 1
        while b <= self.limit:
            if b % 2 == 0:
                total_sum += b
            a, b = b, a + b
        return total_sum


value = fibbunacci(4000000)
print(value.functionsolve())
